### ISSUE TITLE
Software UART

### ISSUE THREAD

**Issue by tedbarth** [rakeshpai/pi-gpio#55] opened 2016-07-09 14:34 UTC
Is it possible to use pi-gpio to create a software UART?
Is the library fast enough?

That would be really cool.
Anyway, great work!

**Comment by tjanson** [comment] 2016-07-13 15:24
I’ve used the library for communications with about 0.3 millisecond precision and had no problems. Thus my guess is that UART at lower rates is possible, but I’m not sure it’ll be fast enough for what you have in mind.

Also note that this project is effectively abandoned (or at least “on hiatus”).

I’ll close this for now (since it’s not a bug, and I’m afraid there won’t be a more specific answer), but feel free to re-open if you have further questions. And of course feel free to update if you do try a UART implementation.

**Closed as completed by tjanson** 2016-07-13 15:24 UTC
Labels: question
